version: 2.1

commands:
  merge-branch:
    parameters:
      branch:
        type: string
    steps:
      - run:
          name: Checkout Code (esmf-test-artifacts)
          command: mkdir -p ~/.ssh;echo "Host *" > ~/.ssh/config; echo "  StrictHostKeyChecking no" >> ~/.ssh/config;cd ~;echo $PWD;git clone git@github.com:esmf-org/esmf-test-artifacts.git;echo $PWD
      - run:
          name: run scripts
          command: cd ~;echo $PWD;ls;cd esmf-test-artifacts;echo $PWD;ls -la;git branch;ls -l .circleci;./.circleci/runscp.sh

jobs:
  mt-test:
    docker:
      - image: cimg/base:stable-20.04
    resource_class: large
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7b:d8:04:5d:01:42:c2:0f:cc:c7:b1:ec:95:39:2d:4b"
      - merge-branch:
          branch: chianti

workflows:

  merge-branch:
    jobs:
      - mt-test:
          name: test

