version: 2.1

commands:
  merge-branch:
    parameters:
      branch:
        type: string
    steps:
      - run:
          name: Checkout Code (esmf-test-artifacts)
          command: mkdir -p ~/.ssh;echo "Host *" > ~/.ssh/config; echo "  StrictHostKeyChecking no" >> ~/.ssh/config;cd ~;echo $PWD;git clone -b ${CIRCLE_BRANCH} git@github.com:esmf-org/esmf-test-artifacts.git;echo $PWD
      - run:
          name: run scripts
          command: cd ~;echo $PWD;ls;cd esmf-test-artifacts;echo $PWD;ls -l;git branch;ls -l .circleci;./.circleci/runscp.sh

jobs:
  mt-test:
    docker:
      - image: docker:stable-git
    steps:
      - add_ssh_keys:
          fingerprints:
            - "22:a5:e1:d5:16:a7:f3:fe:45:8e:d8:80:55:48:a6:3e"
      - merge-branch:
          branch: chianti

workflows:

  merge-branch:
    jobs:
      - mt-test:
          name: test

